# Utiliser une image Ruby officielle
FROM ruby:3.1

# Installer les dépendances nécessaires
RUN apt-get update && \
    apt-get install -y build-essential libmariadb-dev

# Installer la gem mysql2
RUN gem install mysql2

# Copier tous les fichiers des répertoires scripts_rb et logs
COPY scripts_rb/ /usr/src/app/scripts_rb/
COPY logs/ /usr/src/app/logs/

# Configurer le répertoire de travail
WORKDIR /usr/src/app

# Maintenir le conteneur actif
CMD ["sleep", "infinity"]
